module.exports = (sequelize, DataTypes) => {
    const HorsesRace = sequelize.define('HorsesRace', {
        idSportinglife: DataTypes.INTEGER,
        date: DataTypes.DATE,
        hour: DataTypes.STRING,
        name: DataTypes.STRING,
        place: DataTypes.STRING,
        track: DataTypes.STRING,
        age: DataTypes.STRING,
        amountRunners: DataTypes.INTEGER,
        precision: DataTypes.STRING,
        oddP1: DataTypes.FLOAT,
        oddP2: DataTypes.FLOAT,
        oddP3: DataTypes.FLOAT,
        oddP4: DataTypes.FLOAT,
        oddP5: DataTypes.FLOAT,
        oddP6: DataTypes.FLOAT,
        oddP7: DataTypes.FLOAT,
        oddP8: DataTypes.FLOAT,
        oddP9: DataTypes.FLOAT,
        oddP10: DataTypes.FLOAT,
        oddP11: DataTypes.FLOAT,
        oddP12: DataTypes.FLOAT,
        oddP1Dec: DataTypes.STRING,
        oddP2Dec: DataTypes.STRING,
        oddP3Dec: DataTypes.STRING,
        oddP4Dec: DataTypes.STRING,
        oddP5Dec: DataTypes.STRING,
        oddP6Dec: DataTypes.STRING,
        oddP7Dec: DataTypes.STRING,
        oddP8Dec: DataTypes.STRING,
        oddP9Dec: DataTypes.STRING,
        oddP10Dec: DataTypes.STRING,
        oddP11Dec: DataTypes.STRING,
        oddP12Dec: DataTypes.STRING,
        premiumP1: DataTypes.STRING,
        premiumP2: DataTypes.STRING,
        premiumP3: DataTypes.STRING,
        premiumP4: DataTypes.STRING,
        premiumP5: DataTypes.STRING,
        premiumP6: DataTypes.STRING,
        premiumP7: DataTypes.STRING,
        premiumP8: DataTypes.STRING,
        premiumP9: DataTypes.STRING,
        premiumP10: DataTypes.STRING,
    });

    return HorsesRace;
}